name: VMX Test
favicon: null
layout_spectrum: 0.6963358819484711
typography_spectrum: 0.0056655025109648705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2596084240358323
  lightness: 0.5495088149327785
  saturation: 0.5476108409930021
  rhythmicContrast: 0.5129880423191935
purpose: []
